version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: drp_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  db_readonly:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_read_only:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: drp_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  metabase:
    image: metabase/metabase
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: drp_development
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: password
      MB_DB_HOST: db_readonly

  web:
    build:
      context: rails/.
    working_dir: /mnt/rails
    env_file: .env
    # command: bundle exec rails s -p 5001 -b '0.0.0.0'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails:/mnt/rails
    ports:
      - "3000:3000"
    links:
      - db
      - db_readonly
    depends_on:
      - db
      - db_readonly

volumes:
  postgres_data:
  postgres_data_read_only:
